import canonicalLaneMathlib.AdmissibleClass
import MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean.ReplicationOriginsPackage
import MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean.InitiationComplexAssembly
import MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean.HelicaseLoadingAndUnwinding
import MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean.ReplicationForkProgression
import MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean.ReplicationTermination
import MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean.RegulationOfOriginActivation

namespace HautevilleHouse
namespace MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean

def ConstrainedReplicationOriginsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_replication_origins_endgame (A : AdmissibleClass) :
    ConstrainedReplicationOriginsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end MolecularBiologyOriginsReplicationLemmaCanonicalLaneLean
end HautevilleHouse